(cl:in-package tm_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          IS_SVR_CONNECTED-VAL
          IS_SVR_CONNECTED
          IS_SCT_CONNECTED-VAL
          IS_SCT_CONNECTED
          TMSRV_CPERR-VAL
          TMSRV_CPERR
          TMSCRIPT_CPERR-VAL
          TMSCRIPT_CPERR
          TMSRV_DATAERR-VAL
          TMSRV_DATAERR
          TMSCRIPT_DATAERR-VAL
          TMSCRIPT_DATAERR
          MAX_NOT_CONNECT_IN_S-VAL
          MAX_NOT_CONNECT_IN_S
          DISCONNECTION_TIMES-VAL
          DISCONNECTION_TIMES
          JOINT_POS-VAL
          JOINT_POS
          JOINT_VEL-VAL
          JOINT_VEL
          JOINT_TOR-VAL
          JOINT_TOR
          TOOL0_POSE-VAL
          TOOL0_POSE
          TOOL_POSE-VAL
          TOOL_POSE
          TCP_SPEED-VAL
          TCP_SPEED
          TCP_FORCE-VAL
          TCP_FORCE
          JOINT_TOR_AVERAGE-VAL
          JOINT_TOR_AVERAGE
          JOINT_TOR_MIN-VAL
          JOINT_TOR_MIN
          JOINT_TOR_MAX-VAL
          JOINT_TOR_MAX
          ROBOT_LINK-VAL
          ROBOT_LINK
          IS_DATA_TABLE_CORRECT-VAL
          IS_DATA_TABLE_CORRECT
          ROBOT_ERROR-VAL
          ROBOT_ERROR
          PROJECT_RUN-VAL
          PROJECT_RUN
          PROJECT_PAUSE-VAL
          PROJECT_PAUSE
          SAFETYGUARD_A-VAL
          SAFETYGUARD_A
          E_STOP-VAL
          E_STOP
          CAMERA_LIGHT-VAL
          CAMERA_LIGHT
          ERROR_CODE-VAL
          ERROR_CODE
          PROJECT_SPEED-VAL
          PROJECT_SPEED
          MA_MODE-VAL
          MA_MODE
          ROBOT_LIGHT-VAL
          ROBOT_LIGHT
          CB_DIGITAL_OUTPUT-VAL
          CB_DIGITAL_OUTPUT
          CB_DIGITAL_INPUT-VAL
          CB_DIGITAL_INPUT
          CB_ANALOG_OUTPUT-VAL
          CB_ANALOG_OUTPUT
          CB_ANALOG_INPUT-VAL
          CB_ANALOG_INPUT
          EE_DIGITAL_OUTPUT-VAL
          EE_DIGITAL_OUTPUT
          EE_DIGITAL_INPUT-VAL
          EE_DIGITAL_INPUT
          EE_ANALOG_OUTPUT-VAL
          EE_ANALOG_OUTPUT
          EE_ANALOG_INPUT-VAL
          EE_ANALOG_INPUT
          ERROR_CONTENT-VAL
          ERROR_CONTENT
))