// Generated by gencpp from file tm_msgs/AskItem.msg
// DO NOT EDIT!


#ifndef TM_MSGS_MESSAGE_ASKITEM_H
#define TM_MSGS_MESSAGE_ASKITEM_H

#include <ros/service_traits.h>


#include <tm_msgs/AskItemRequest.h>
#include <tm_msgs/AskItemResponse.h>


namespace tm_msgs
{

struct AskItem
{

typedef AskItemRequest Request;
typedef AskItemResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AskItem
} // namespace tm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tm_msgs::AskItem > {
  static const char* value()
  {
    return "b3422b8e3441a8072a0236251e9f0ee1";
  }

  static const char* value(const ::tm_msgs::AskItem&) { return value(); }
};

template<>
struct DataType< ::tm_msgs::AskItem > {
  static const char* value()
  {
    return "tm_msgs/AskItem";
  }

  static const char* value(const ::tm_msgs::AskItem&) { return value(); }
};


// service_traits::MD5Sum< ::tm_msgs::AskItemRequest> should match
// service_traits::MD5Sum< ::tm_msgs::AskItem >
template<>
struct MD5Sum< ::tm_msgs::AskItemRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::AskItem >::value();
  }
  static const char* value(const ::tm_msgs::AskItemRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::AskItemRequest> should match
// service_traits::DataType< ::tm_msgs::AskItem >
template<>
struct DataType< ::tm_msgs::AskItemRequest>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::AskItem >::value();
  }
  static const char* value(const ::tm_msgs::AskItemRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tm_msgs::AskItemResponse> should match
// service_traits::MD5Sum< ::tm_msgs::AskItem >
template<>
struct MD5Sum< ::tm_msgs::AskItemResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::AskItem >::value();
  }
  static const char* value(const ::tm_msgs::AskItemResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::AskItemResponse> should match
// service_traits::DataType< ::tm_msgs::AskItem >
template<>
struct DataType< ::tm_msgs::AskItemResponse>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::AskItem >::value();
  }
  static const char* value(const ::tm_msgs::AskItemResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TM_MSGS_MESSAGE_ASKITEM_H
