// Generated by gencpp from file tm_msgs/AskSta.msg
// DO NOT EDIT!


#ifndef TM_MSGS_MESSAGE_ASKSTA_H
#define TM_MSGS_MESSAGE_ASKSTA_H

#include <ros/service_traits.h>


#include <tm_msgs/AskStaRequest.h>
#include <tm_msgs/AskStaResponse.h>


namespace tm_msgs
{

struct AskSta
{

typedef AskStaRequest Request;
typedef AskStaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AskSta
} // namespace tm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tm_msgs::AskSta > {
  static const char* value()
  {
    return "8d2ef2c8296a1b6a1aea258b0876a209";
  }

  static const char* value(const ::tm_msgs::AskSta&) { return value(); }
};

template<>
struct DataType< ::tm_msgs::AskSta > {
  static const char* value()
  {
    return "tm_msgs/AskSta";
  }

  static const char* value(const ::tm_msgs::AskSta&) { return value(); }
};


// service_traits::MD5Sum< ::tm_msgs::AskStaRequest> should match
// service_traits::MD5Sum< ::tm_msgs::AskSta >
template<>
struct MD5Sum< ::tm_msgs::AskStaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::AskSta >::value();
  }
  static const char* value(const ::tm_msgs::AskStaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::AskStaRequest> should match
// service_traits::DataType< ::tm_msgs::AskSta >
template<>
struct DataType< ::tm_msgs::AskStaRequest>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::AskSta >::value();
  }
  static const char* value(const ::tm_msgs::AskStaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tm_msgs::AskStaResponse> should match
// service_traits::MD5Sum< ::tm_msgs::AskSta >
template<>
struct MD5Sum< ::tm_msgs::AskStaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::AskSta >::value();
  }
  static const char* value(const ::tm_msgs::AskStaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::AskStaResponse> should match
// service_traits::DataType< ::tm_msgs::AskSta >
template<>
struct DataType< ::tm_msgs::AskStaResponse>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::AskSta >::value();
  }
  static const char* value(const ::tm_msgs::AskStaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TM_MSGS_MESSAGE_ASKSTA_H
