// Generated by gencpp from file tm_msgs/ConnectTM.msg
// DO NOT EDIT!


#ifndef TM_MSGS_MESSAGE_CONNECTTM_H
#define TM_MSGS_MESSAGE_CONNECTTM_H

#include <ros/service_traits.h>


#include <tm_msgs/ConnectTMRequest.h>
#include <tm_msgs/ConnectTMResponse.h>


namespace tm_msgs
{

struct ConnectTM
{

typedef ConnectTMRequest Request;
typedef ConnectTMResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ConnectTM
} // namespace tm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tm_msgs::ConnectTM > {
  static const char* value()
  {
    return "0d50ce933552e4d5e66858757bce799c";
  }

  static const char* value(const ::tm_msgs::ConnectTM&) { return value(); }
};

template<>
struct DataType< ::tm_msgs::ConnectTM > {
  static const char* value()
  {
    return "tm_msgs/ConnectTM";
  }

  static const char* value(const ::tm_msgs::ConnectTM&) { return value(); }
};


// service_traits::MD5Sum< ::tm_msgs::ConnectTMRequest> should match
// service_traits::MD5Sum< ::tm_msgs::ConnectTM >
template<>
struct MD5Sum< ::tm_msgs::ConnectTMRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::ConnectTM >::value();
  }
  static const char* value(const ::tm_msgs::ConnectTMRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::ConnectTMRequest> should match
// service_traits::DataType< ::tm_msgs::ConnectTM >
template<>
struct DataType< ::tm_msgs::ConnectTMRequest>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::ConnectTM >::value();
  }
  static const char* value(const ::tm_msgs::ConnectTMRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tm_msgs::ConnectTMResponse> should match
// service_traits::MD5Sum< ::tm_msgs::ConnectTM >
template<>
struct MD5Sum< ::tm_msgs::ConnectTMResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::ConnectTM >::value();
  }
  static const char* value(const ::tm_msgs::ConnectTMResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::ConnectTMResponse> should match
// service_traits::DataType< ::tm_msgs::ConnectTM >
template<>
struct DataType< ::tm_msgs::ConnectTMResponse>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::ConnectTM >::value();
  }
  static const char* value(const ::tm_msgs::ConnectTMResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TM_MSGS_MESSAGE_CONNECTTM_H
