// Generated by gencpp from file tm_msgs/JointMove.msg
// DO NOT EDIT!


#ifndef TM_MSGS_MESSAGE_JOINTMOVE_H
#define TM_MSGS_MESSAGE_JOINTMOVE_H

#include <ros/service_traits.h>


#include <tm_msgs/JointMoveRequest.h>
#include <tm_msgs/JointMoveResponse.h>


namespace tm_msgs
{

struct JointMove
{

typedef JointMoveRequest Request;
typedef JointMoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JointMove
} // namespace tm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tm_msgs::JointMove > {
  static const char* value()
  {
    return "07f94568e46947f8fdd61bbf89ecd59c";
  }

  static const char* value(const ::tm_msgs::JointMove&) { return value(); }
};

template<>
struct DataType< ::tm_msgs::JointMove > {
  static const char* value()
  {
    return "tm_msgs/JointMove";
  }

  static const char* value(const ::tm_msgs::JointMove&) { return value(); }
};


// service_traits::MD5Sum< ::tm_msgs::JointMoveRequest> should match
// service_traits::MD5Sum< ::tm_msgs::JointMove >
template<>
struct MD5Sum< ::tm_msgs::JointMoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::JointMove >::value();
  }
  static const char* value(const ::tm_msgs::JointMoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::JointMoveRequest> should match
// service_traits::DataType< ::tm_msgs::JointMove >
template<>
struct DataType< ::tm_msgs::JointMoveRequest>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::JointMove >::value();
  }
  static const char* value(const ::tm_msgs::JointMoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tm_msgs::JointMoveResponse> should match
// service_traits::MD5Sum< ::tm_msgs::JointMove >
template<>
struct MD5Sum< ::tm_msgs::JointMoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::JointMove >::value();
  }
  static const char* value(const ::tm_msgs::JointMoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::JointMoveResponse> should match
// service_traits::DataType< ::tm_msgs::JointMove >
template<>
struct DataType< ::tm_msgs::JointMoveResponse>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::JointMove >::value();
  }
  static const char* value(const ::tm_msgs::JointMoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TM_MSGS_MESSAGE_JOINTMOVE_H
