// Generated by gencpp from file tm_msgs/SendScript.msg
// DO NOT EDIT!


#ifndef TM_MSGS_MESSAGE_SENDSCRIPT_H
#define TM_MSGS_MESSAGE_SENDSCRIPT_H

#include <ros/service_traits.h>


#include <tm_msgs/SendScriptRequest.h>
#include <tm_msgs/SendScriptResponse.h>


namespace tm_msgs
{

struct SendScript
{

typedef SendScriptRequest Request;
typedef SendScriptResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendScript
} // namespace tm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tm_msgs::SendScript > {
  static const char* value()
  {
    return "f7c1ec2437ee83ce8a1998e89ee510ca";
  }

  static const char* value(const ::tm_msgs::SendScript&) { return value(); }
};

template<>
struct DataType< ::tm_msgs::SendScript > {
  static const char* value()
  {
    return "tm_msgs/SendScript";
  }

  static const char* value(const ::tm_msgs::SendScript&) { return value(); }
};


// service_traits::MD5Sum< ::tm_msgs::SendScriptRequest> should match
// service_traits::MD5Sum< ::tm_msgs::SendScript >
template<>
struct MD5Sum< ::tm_msgs::SendScriptRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::SendScript >::value();
  }
  static const char* value(const ::tm_msgs::SendScriptRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::SendScriptRequest> should match
// service_traits::DataType< ::tm_msgs::SendScript >
template<>
struct DataType< ::tm_msgs::SendScriptRequest>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::SendScript >::value();
  }
  static const char* value(const ::tm_msgs::SendScriptRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tm_msgs::SendScriptResponse> should match
// service_traits::MD5Sum< ::tm_msgs::SendScript >
template<>
struct MD5Sum< ::tm_msgs::SendScriptResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::SendScript >::value();
  }
  static const char* value(const ::tm_msgs::SendScriptResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::SendScriptResponse> should match
// service_traits::DataType< ::tm_msgs::SendScript >
template<>
struct DataType< ::tm_msgs::SendScriptResponse>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::SendScript >::value();
  }
  static const char* value(const ::tm_msgs::SendScriptResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TM_MSGS_MESSAGE_SENDSCRIPT_H
