// Generated by gencpp from file tm_msgs/SetPositions.msg
// DO NOT EDIT!


#ifndef TM_MSGS_MESSAGE_SETPOSITIONS_H
#define TM_MSGS_MESSAGE_SETPOSITIONS_H

#include <ros/service_traits.h>


#include <tm_msgs/SetPositionsRequest.h>
#include <tm_msgs/SetPositionsResponse.h>


namespace tm_msgs
{

struct SetPositions
{

typedef SetPositionsRequest Request;
typedef SetPositionsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPositions
} // namespace tm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tm_msgs::SetPositions > {
  static const char* value()
  {
    return "0bbf77b368ab8921b229f24921a6e9d7";
  }

  static const char* value(const ::tm_msgs::SetPositions&) { return value(); }
};

template<>
struct DataType< ::tm_msgs::SetPositions > {
  static const char* value()
  {
    return "tm_msgs/SetPositions";
  }

  static const char* value(const ::tm_msgs::SetPositions&) { return value(); }
};


// service_traits::MD5Sum< ::tm_msgs::SetPositionsRequest> should match
// service_traits::MD5Sum< ::tm_msgs::SetPositions >
template<>
struct MD5Sum< ::tm_msgs::SetPositionsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::SetPositions >::value();
  }
  static const char* value(const ::tm_msgs::SetPositionsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::SetPositionsRequest> should match
// service_traits::DataType< ::tm_msgs::SetPositions >
template<>
struct DataType< ::tm_msgs::SetPositionsRequest>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::SetPositions >::value();
  }
  static const char* value(const ::tm_msgs::SetPositionsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tm_msgs::SetPositionsResponse> should match
// service_traits::MD5Sum< ::tm_msgs::SetPositions >
template<>
struct MD5Sum< ::tm_msgs::SetPositionsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::SetPositions >::value();
  }
  static const char* value(const ::tm_msgs::SetPositionsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::SetPositionsResponse> should match
// service_traits::DataType< ::tm_msgs::SetPositions >
template<>
struct DataType< ::tm_msgs::SetPositionsResponse>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::SetPositions >::value();
  }
  static const char* value(const ::tm_msgs::SetPositionsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TM_MSGS_MESSAGE_SETPOSITIONS_H
