// Generated by gencpp from file tm_msgs/StaResponse.msg
// DO NOT EDIT!


#ifndef TM_MSGS_MESSAGE_STARESPONSE_H
#define TM_MSGS_MESSAGE_STARESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tm_msgs
{
template <class ContainerAllocator>
struct StaResponse_
{
  typedef StaResponse_<ContainerAllocator> Type;

  StaResponse_()
    : header()
    , subcmd()
    , subdata()  {
    }
  StaResponse_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , subcmd(_alloc)
    , subdata(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _subcmd_type;
  _subcmd_type subcmd;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _subdata_type;
  _subdata_type subdata;





  typedef boost::shared_ptr< ::tm_msgs::StaResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tm_msgs::StaResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StaResponse_

typedef ::tm_msgs::StaResponse_<std::allocator<void> > StaResponse;

typedef boost::shared_ptr< ::tm_msgs::StaResponse > StaResponsePtr;
typedef boost::shared_ptr< ::tm_msgs::StaResponse const> StaResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tm_msgs::StaResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tm_msgs::StaResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tm_msgs::StaResponse_<ContainerAllocator1> & lhs, const ::tm_msgs::StaResponse_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.subcmd == rhs.subcmd &&
    lhs.subdata == rhs.subdata;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tm_msgs::StaResponse_<ContainerAllocator1> & lhs, const ::tm_msgs::StaResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tm_msgs::StaResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tm_msgs::StaResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tm_msgs::StaResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tm_msgs::StaResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_msgs::StaResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_msgs::StaResponse_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tm_msgs::StaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a5171002fa543efe0e7302c1efd2051";
  }

  static const char* value(const ::tm_msgs::StaResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a5171002fa543efULL;
  static const uint64_t static_value2 = 0xe0e7302c1efd2051ULL;
};

template<class ContainerAllocator>
struct DataType< ::tm_msgs::StaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tm_msgs/StaResponse";
  }

  static const char* value(const ::tm_msgs::StaResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tm_msgs::StaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# For SetEvent TAG / AskSta service\n"
"# More details please refer to the TM_Robot_Expression.pdf(1.76 rev1.00) Chapter 7.5\n"
"\n"
"Header header\n"
"\n"
"string subcmd\n"
"string subdata\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::tm_msgs::StaResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tm_msgs::StaResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.subcmd);
      stream.next(m.subdata);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StaResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tm_msgs::StaResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tm_msgs::StaResponse_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "subcmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.subcmd);
    s << indent << "subdata: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.subdata);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TM_MSGS_MESSAGE_STARESPONSE_H
