// Generated by gencpp from file tm_msgs/AskStaRequest.msg
// DO NOT EDIT!


#ifndef TM_MSGS_MESSAGE_ASKSTAREQUEST_H
#define TM_MSGS_MESSAGE_ASKSTAREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tm_msgs
{
template <class ContainerAllocator>
struct AskStaRequest_
{
  typedef AskStaRequest_<ContainerAllocator> Type;

  AskStaRequest_()
    : subcmd()
    , subdata()
    , wait_time(0.0)  {
    }
  AskStaRequest_(const ContainerAllocator& _alloc)
    : subcmd(_alloc)
    , subdata(_alloc)
    , wait_time(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _subcmd_type;
  _subcmd_type subcmd;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _subdata_type;
  _subdata_type subdata;

   typedef double _wait_time_type;
  _wait_time_type wait_time;





  typedef boost::shared_ptr< ::tm_msgs::AskStaRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tm_msgs::AskStaRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AskStaRequest_

typedef ::tm_msgs::AskStaRequest_<std::allocator<void> > AskStaRequest;

typedef boost::shared_ptr< ::tm_msgs::AskStaRequest > AskStaRequestPtr;
typedef boost::shared_ptr< ::tm_msgs::AskStaRequest const> AskStaRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tm_msgs::AskStaRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tm_msgs::AskStaRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tm_msgs::AskStaRequest_<ContainerAllocator1> & lhs, const ::tm_msgs::AskStaRequest_<ContainerAllocator2> & rhs)
{
  return lhs.subcmd == rhs.subcmd &&
    lhs.subdata == rhs.subdata &&
    lhs.wait_time == rhs.wait_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tm_msgs::AskStaRequest_<ContainerAllocator1> & lhs, const ::tm_msgs::AskStaRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tm_msgs::AskStaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tm_msgs::AskStaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tm_msgs::AskStaRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tm_msgs::AskStaRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_msgs::AskStaRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_msgs::AskStaRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tm_msgs::AskStaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4d332df23aae69bb9755f2fba3f4522";
  }

  static const char* value(const ::tm_msgs::AskStaRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4d332df23aae69bULL;
  static const uint64_t static_value2 = 0xb9755f2fba3f4522ULL;
};

template<class ContainerAllocator>
struct DataType< ::tm_msgs::AskStaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tm_msgs/AskStaRequest";
  }

  static const char* value(const ::tm_msgs::AskStaRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tm_msgs::AskStaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Ask: request 'Read' sta\n"
"# More details please refer to the TM_Robot_Expression.pdf(1.76 rev1.00) Chapter 7.5 TMSTA\n"
"# wait_time : set wait time.\n"
"\n"
"string subcmd\n"
"string subdata\n"
"\n"
"float64 wait_time\n"
"\n"
;
  }

  static const char* value(const ::tm_msgs::AskStaRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tm_msgs::AskStaRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.subcmd);
      stream.next(m.subdata);
      stream.next(m.wait_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AskStaRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tm_msgs::AskStaRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tm_msgs::AskStaRequest_<ContainerAllocator>& v)
  {
    s << indent << "subcmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.subcmd);
    s << indent << "subdata: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.subdata);
    s << indent << "wait_time: ";
    Printer<double>::stream(s, indent + "  ", v.wait_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TM_MSGS_MESSAGE_ASKSTAREQUEST_H
