// Generated by gencpp from file tm_msgs/CartesianMove.msg
// DO NOT EDIT!


#ifndef TM_MSGS_MESSAGE_CARTESIANMOVE_H
#define TM_MSGS_MESSAGE_CARTESIANMOVE_H

#include <ros/service_traits.h>


#include <tm_msgs/CartesianMoveRequest.h>
#include <tm_msgs/CartesianMoveResponse.h>


namespace tm_msgs
{

struct CartesianMove
{

typedef CartesianMoveRequest Request;
typedef CartesianMoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CartesianMove
} // namespace tm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tm_msgs::CartesianMove > {
  static const char* value()
  {
    return "7c6bc7eb9aa36ece17e84459bdba640a";
  }

  static const char* value(const ::tm_msgs::CartesianMove&) { return value(); }
};

template<>
struct DataType< ::tm_msgs::CartesianMove > {
  static const char* value()
  {
    return "tm_msgs/CartesianMove";
  }

  static const char* value(const ::tm_msgs::CartesianMove&) { return value(); }
};


// service_traits::MD5Sum< ::tm_msgs::CartesianMoveRequest> should match
// service_traits::MD5Sum< ::tm_msgs::CartesianMove >
template<>
struct MD5Sum< ::tm_msgs::CartesianMoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::CartesianMove >::value();
  }
  static const char* value(const ::tm_msgs::CartesianMoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::CartesianMoveRequest> should match
// service_traits::DataType< ::tm_msgs::CartesianMove >
template<>
struct DataType< ::tm_msgs::CartesianMoveRequest>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::CartesianMove >::value();
  }
  static const char* value(const ::tm_msgs::CartesianMoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tm_msgs::CartesianMoveResponse> should match
// service_traits::MD5Sum< ::tm_msgs::CartesianMove >
template<>
struct MD5Sum< ::tm_msgs::CartesianMoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::CartesianMove >::value();
  }
  static const char* value(const ::tm_msgs::CartesianMoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::CartesianMoveResponse> should match
// service_traits::DataType< ::tm_msgs::CartesianMove >
template<>
struct DataType< ::tm_msgs::CartesianMoveResponse>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::CartesianMove >::value();
  }
  static const char* value(const ::tm_msgs::CartesianMoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TM_MSGS_MESSAGE_CARTESIANMOVE_H
