// Generated by gencpp from file tm_msgs/CartesianMoveRequest.msg
// DO NOT EDIT!


#ifndef TM_MSGS_MESSAGE_CARTESIANMOVEREQUEST_H
#define TM_MSGS_MESSAGE_CARTESIANMOVEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace tm_msgs
{
template <class ContainerAllocator>
struct CartesianMoveRequest_
{
  typedef CartesianMoveRequest_<ContainerAllocator> Type;

  CartesianMoveRequest_()
    : poseTarget()  {
    }
  CartesianMoveRequest_(const ContainerAllocator& _alloc)
    : poseTarget(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _poseTarget_type;
  _poseTarget_type poseTarget;





  typedef boost::shared_ptr< ::tm_msgs::CartesianMoveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tm_msgs::CartesianMoveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CartesianMoveRequest_

typedef ::tm_msgs::CartesianMoveRequest_<std::allocator<void> > CartesianMoveRequest;

typedef boost::shared_ptr< ::tm_msgs::CartesianMoveRequest > CartesianMoveRequestPtr;
typedef boost::shared_ptr< ::tm_msgs::CartesianMoveRequest const> CartesianMoveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tm_msgs::CartesianMoveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tm_msgs::CartesianMoveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tm_msgs::CartesianMoveRequest_<ContainerAllocator1> & lhs, const ::tm_msgs::CartesianMoveRequest_<ContainerAllocator2> & rhs)
{
  return lhs.poseTarget == rhs.poseTarget;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tm_msgs::CartesianMoveRequest_<ContainerAllocator1> & lhs, const ::tm_msgs::CartesianMoveRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tm_msgs::CartesianMoveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tm_msgs::CartesianMoveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tm_msgs::CartesianMoveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tm_msgs::CartesianMoveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_msgs::CartesianMoveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_msgs::CartesianMoveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tm_msgs::CartesianMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46373f83afb6c46513d3d786edd59f39";
  }

  static const char* value(const ::tm_msgs::CartesianMoveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46373f83afb6c465ULL;
  static const uint64_t static_value2 = 0x13d3d786edd59f39ULL;
};

template<class ContainerAllocator>
struct DataType< ::tm_msgs::CartesianMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tm_msgs/CartesianMoveRequest";
  }

  static const char* value(const ::tm_msgs::CartesianMoveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tm_msgs::CartesianMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose poseTarget\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::tm_msgs::CartesianMoveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tm_msgs::CartesianMoveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.poseTarget);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CartesianMoveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tm_msgs::CartesianMoveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tm_msgs::CartesianMoveRequest_<ContainerAllocator>& v)
  {
    s << indent << "poseTarget: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.poseTarget);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TM_MSGS_MESSAGE_CARTESIANMOVEREQUEST_H
