// Generated by gencpp from file tm_msgs/JointMoveRequest.msg
// DO NOT EDIT!


#ifndef TM_MSGS_MESSAGE_JOINTMOVEREQUEST_H
#define TM_MSGS_MESSAGE_JOINTMOVEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/JointState.h>

namespace tm_msgs
{
template <class ContainerAllocator>
struct JointMoveRequest_
{
  typedef JointMoveRequest_<ContainerAllocator> Type;

  JointMoveRequest_()
    : jointTarget()  {
    }
  JointMoveRequest_(const ContainerAllocator& _alloc)
    : jointTarget(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::JointState_<ContainerAllocator>  _jointTarget_type;
  _jointTarget_type jointTarget;





  typedef boost::shared_ptr< ::tm_msgs::JointMoveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tm_msgs::JointMoveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct JointMoveRequest_

typedef ::tm_msgs::JointMoveRequest_<std::allocator<void> > JointMoveRequest;

typedef boost::shared_ptr< ::tm_msgs::JointMoveRequest > JointMoveRequestPtr;
typedef boost::shared_ptr< ::tm_msgs::JointMoveRequest const> JointMoveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tm_msgs::JointMoveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tm_msgs::JointMoveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tm_msgs::JointMoveRequest_<ContainerAllocator1> & lhs, const ::tm_msgs::JointMoveRequest_<ContainerAllocator2> & rhs)
{
  return lhs.jointTarget == rhs.jointTarget;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tm_msgs::JointMoveRequest_<ContainerAllocator1> & lhs, const ::tm_msgs::JointMoveRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tm_msgs::JointMoveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tm_msgs::JointMoveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tm_msgs::JointMoveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tm_msgs::JointMoveRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_msgs::JointMoveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_msgs::JointMoveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tm_msgs::JointMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cdca231acb928c832450acedf16ebc56";
  }

  static const char* value(const ::tm_msgs::JointMoveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcdca231acb928c83ULL;
  static const uint64_t static_value2 = 0x2450acedf16ebc56ULL;
};

template<class ContainerAllocator>
struct DataType< ::tm_msgs::JointMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tm_msgs/JointMoveRequest";
  }

  static const char* value(const ::tm_msgs::JointMoveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tm_msgs::JointMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/JointState jointTarget\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/JointState\n"
"# This is a message that holds data to describe the state of a set of torque controlled joints. \n"
"#\n"
"# The state of each joint (revolute or prismatic) is defined by:\n"
"#  * the position of the joint (rad or m),\n"
"#  * the velocity of the joint (rad/s or m/s) and \n"
"#  * the effort that is applied in the joint (Nm or N).\n"
"#\n"
"# Each joint is uniquely identified by its name\n"
"# The header specifies the time at which the joint states were recorded. All the joint states\n"
"# in one message have to be recorded at the same time.\n"
"#\n"
"# This message consists of a multiple arrays, one for each part of the joint state. \n"
"# The goal is to make each of the fields optional. When e.g. your joints have no\n"
"# effort associated with them, you can leave the effort array empty. \n"
"#\n"
"# All arrays in this message should have the same size, or be empty.\n"
"# This is the only way to uniquely associate the joint name with the correct\n"
"# states.\n"
"\n"
"\n"
"Header header\n"
"\n"
"string[] name\n"
"float64[] position\n"
"float64[] velocity\n"
"float64[] effort\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::tm_msgs::JointMoveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tm_msgs::JointMoveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.jointTarget);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointMoveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tm_msgs::JointMoveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tm_msgs::JointMoveRequest_<ContainerAllocator>& v)
  {
    s << indent << "jointTarget: ";
    s << std::endl;
    Printer< ::sensor_msgs::JointState_<ContainerAllocator> >::stream(s, indent + "  ", v.jointTarget);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TM_MSGS_MESSAGE_JOINTMOVEREQUEST_H
