// Generated by gencpp from file tm_msgs/SctResponse.msg
// DO NOT EDIT!


#ifndef TM_MSGS_MESSAGE_SCTRESPONSE_H
#define TM_MSGS_MESSAGE_SCTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tm_msgs
{
template <class ContainerAllocator>
struct SctResponse_
{
  typedef SctResponse_<ContainerAllocator> Type;

  SctResponse_()
    : header()
    , id()
    , script()  {
    }
  SctResponse_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(_alloc)
    , script(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _script_type;
  _script_type script;





  typedef boost::shared_ptr< ::tm_msgs::SctResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tm_msgs::SctResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SctResponse_

typedef ::tm_msgs::SctResponse_<std::allocator<void> > SctResponse;

typedef boost::shared_ptr< ::tm_msgs::SctResponse > SctResponsePtr;
typedef boost::shared_ptr< ::tm_msgs::SctResponse const> SctResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tm_msgs::SctResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tm_msgs::SctResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tm_msgs::SctResponse_<ContainerAllocator1> & lhs, const ::tm_msgs::SctResponse_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.script == rhs.script;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tm_msgs::SctResponse_<ContainerAllocator1> & lhs, const ::tm_msgs::SctResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tm_msgs::SctResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tm_msgs::SctResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tm_msgs::SctResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tm_msgs::SctResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_msgs::SctResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tm_msgs::SctResponse_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tm_msgs::SctResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36fc752cb7af4e35e40e062d5409444d";
  }

  static const char* value(const ::tm_msgs::SctResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36fc752cb7af4e35ULL;
  static const uint64_t static_value2 = 0xe40e062d5409444dULL;
};

template<class ContainerAllocator>
struct DataType< ::tm_msgs::SctResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tm_msgs/SctResponse";
  }

  static const char* value(const ::tm_msgs::SctResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tm_msgs::SctResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# For SendScript / SetXXX service\n"
"# More details please refer to the TM_Robot_Expression.pdf(1.76 rev1.00) Chapter 7.4\n"
"\n"
"Header header\n"
"\n"
"string id\n"
"string script\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::tm_msgs::SctResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tm_msgs::SctResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.script);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SctResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tm_msgs::SctResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tm_msgs::SctResponse_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.id);
    s << indent << "script: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.script);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TM_MSGS_MESSAGE_SCTRESPONSE_H
