// Generated by gencpp from file tm_msgs/SetEvent.msg
// DO NOT EDIT!


#ifndef TM_MSGS_MESSAGE_SETEVENT_H
#define TM_MSGS_MESSAGE_SETEVENT_H

#include <ros/service_traits.h>


#include <tm_msgs/SetEventRequest.h>
#include <tm_msgs/SetEventResponse.h>


namespace tm_msgs
{

struct SetEvent
{

typedef SetEventRequest Request;
typedef SetEventResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetEvent
} // namespace tm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tm_msgs::SetEvent > {
  static const char* value()
  {
    return "62b75d8dc56191f201e7699fc646eb67";
  }

  static const char* value(const ::tm_msgs::SetEvent&) { return value(); }
};

template<>
struct DataType< ::tm_msgs::SetEvent > {
  static const char* value()
  {
    return "tm_msgs/SetEvent";
  }

  static const char* value(const ::tm_msgs::SetEvent&) { return value(); }
};


// service_traits::MD5Sum< ::tm_msgs::SetEventRequest> should match
// service_traits::MD5Sum< ::tm_msgs::SetEvent >
template<>
struct MD5Sum< ::tm_msgs::SetEventRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::SetEvent >::value();
  }
  static const char* value(const ::tm_msgs::SetEventRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::SetEventRequest> should match
// service_traits::DataType< ::tm_msgs::SetEvent >
template<>
struct DataType< ::tm_msgs::SetEventRequest>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::SetEvent >::value();
  }
  static const char* value(const ::tm_msgs::SetEventRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tm_msgs::SetEventResponse> should match
// service_traits::MD5Sum< ::tm_msgs::SetEvent >
template<>
struct MD5Sum< ::tm_msgs::SetEventResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::SetEvent >::value();
  }
  static const char* value(const ::tm_msgs::SetEventResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::SetEventResponse> should match
// service_traits::DataType< ::tm_msgs::SetEvent >
template<>
struct DataType< ::tm_msgs::SetEventResponse>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::SetEvent >::value();
  }
  static const char* value(const ::tm_msgs::SetEventResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TM_MSGS_MESSAGE_SETEVENT_H
