// Generated by gencpp from file tm_msgs/WriteItem.msg
// DO NOT EDIT!


#ifndef TM_MSGS_MESSAGE_WRITEITEM_H
#define TM_MSGS_MESSAGE_WRITEITEM_H

#include <ros/service_traits.h>


#include <tm_msgs/WriteItemRequest.h>
#include <tm_msgs/WriteItemResponse.h>


namespace tm_msgs
{

struct WriteItem
{

typedef WriteItemRequest Request;
typedef WriteItemResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WriteItem
} // namespace tm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tm_msgs::WriteItem > {
  static const char* value()
  {
    return "200255964745879fc25ca887f157e1b3";
  }

  static const char* value(const ::tm_msgs::WriteItem&) { return value(); }
};

template<>
struct DataType< ::tm_msgs::WriteItem > {
  static const char* value()
  {
    return "tm_msgs/WriteItem";
  }

  static const char* value(const ::tm_msgs::WriteItem&) { return value(); }
};


// service_traits::MD5Sum< ::tm_msgs::WriteItemRequest> should match
// service_traits::MD5Sum< ::tm_msgs::WriteItem >
template<>
struct MD5Sum< ::tm_msgs::WriteItemRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::WriteItem >::value();
  }
  static const char* value(const ::tm_msgs::WriteItemRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::WriteItemRequest> should match
// service_traits::DataType< ::tm_msgs::WriteItem >
template<>
struct DataType< ::tm_msgs::WriteItemRequest>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::WriteItem >::value();
  }
  static const char* value(const ::tm_msgs::WriteItemRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tm_msgs::WriteItemResponse> should match
// service_traits::MD5Sum< ::tm_msgs::WriteItem >
template<>
struct MD5Sum< ::tm_msgs::WriteItemResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tm_msgs::WriteItem >::value();
  }
  static const char* value(const ::tm_msgs::WriteItemResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tm_msgs::WriteItemResponse> should match
// service_traits::DataType< ::tm_msgs::WriteItem >
template<>
struct DataType< ::tm_msgs::WriteItemResponse>
{
  static const char* value()
  {
    return DataType< ::tm_msgs::WriteItem >::value();
  }
  static const char* value(const ::tm_msgs::WriteItemResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TM_MSGS_MESSAGE_WRITEITEM_H
